### ISSUE TITLE
per-inspection ignores in rpminspect.yaml do not seem to be being processed properly

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#1069]
**Describe the bug**

Package rpminspect.yaml does not seem to be being read correctly. In particular, the debuginfo ignore list does not seem to be being observed.

**To Reproduce**

```
$ rpminspect --version
rpminspect version 1.9
```

We can run the following command on this file: https://github.com/rpminspect/rpminspect/blob/main/data/generic.yaml
```rpminspect -c data/rpminspect.yaml --dump-config```

and we get the following output:

```
...
per-inspection ignores:
    rpmdeps:
        - /lib/modules/*
        - /usr/lib/debug/.dwz/*
        - /usr/lib/grub/*
```

In the --dump-config output, the per-inspection ignores seem to be attached to the rpmdeps task, and not the debuginfo task (although an examination of the data/generic.yaml file makes one believe that it should be attached to the debug-info task).

Also, gating tests are failing on our current rawhide build of stratisd. Here is our package rpminspect.yaml file, https://src.fedoraproject.org/rpms/stratisd/blob/rawhide/f/rpminspect.yaml, which imitates the data/generic.yaml file, here is the build, https://bodhi.fedoraproject.org/updates/FEDORA-2023-3bdf0589e4, and here are the gating test results, https://artifacts.dev.testing-farm.io/046f68e9-4063-4101-af5c-8d6b34d2e5b2/.  If we run
```rpminspect -c data/rpminspect.yaml --dump-config``` on this rpminspect.yaml file it shows the same wierd behavior, the ignores seem to be attached to the rpmdeps task and not the debuginfo task.

**Expected behavior**
1. Would expect to see per-inspection ignores for debuginfo check, not rpmdeps check, in --dump-config output.
2. Would expect gating tests to pass in rawhide in the referenced stratisd update.

**Environment:**
```
$ uname -a
Linux localhost.localdomain 6.0.13-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 14 16:15:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mulkieran** [comment]
Using as an example our own rpminspect.yaml file:

```
---
inspections:
  # none of our compiled code has an ABI
  abidiff: off
  # at present the wrong debuginfo files are being used to run this check
  annocheck: off
  # the project does not use .desktop files
  desktop: off
  # the project uses no Java
  javabytecode: off

rpmdeps:
  # ignore auto dependencies like: (crate(bindgen/default) >= 0.59.0 with crate(bindgen/default) < 0.60.0~)'
  ignore:
    requires: ^\(crate\(.*\)$

debuginfo:
  # rpminspect error: "Contains .symtab"
  # ignoring because this appears to be a bug in rpmbuild or further down the toolchain
  # https://bugzilla.redhat.com/show_bug.cgi?id=2166149
  ignore:
    - /usr/lib/udev/stratis*
```

The debuginfo output from
```rpminspect -c data/rpminspect.yaml --dump-config```
seems wrong, as mentioned in the statement of the issue, but the output also doesn't seem to reflect the rpmdeps-associated entry at all, either. Here is the output:

```
...
patches:
    file_count_threshold: 20
    line_count_threshold: 5000
rpmdeps:
    Requires: 
per-inspection ignores:
    rpmdeps:
        - /usr/lib/udev/stratis*
        - /usr/lib/udev/stratis*
```

Note that the "Requires:" field associated with rpmdeps is just empty.

Looking at the rpminspect rpmdeps check output in our latest build:
* https://bodhi.fedoraproject.org/updates/FEDORA-2023-11d44a0dbc
* https://artifacts.dev.testing-farm.io/d15f5242-9d0e-4b4d-aca4-f834040702e3/

it really looks like these dependencies are not being ignored, which is what we want, as each one is being reported, whether it changed or not, at the info level.

**Comment by CtrlZmaster** [comment]
I think that I might be hitting the same issue - I'm trying to build pcs for CentOS Stream and rpminspect is failing on an inspection that has excluded files in `rpminspect.yaml`. See [the merge request](https://gitlab.com/redhat/centos-stream/rpms/pcs/-/merge_requests/30) for more details like rpminspect output and config.

[Our `rpminspect.yaml`](https://gitlab.com/redhat/centos-stream/rpms/pcs/-/blob/c9s/rpminspect.yaml) excludes `.erb` files from `xml` and `shellsyntax` inspections. For some reason, the `xml` inspection passes (the rule is applied) while the `shellsyntax` inspection fails (the rule is NOT applied).

I tried running rpminspect locally to see where the issue started. I started downgrading rpminspect and found that the newest build where the `rpminspect.yaml` file works as expected was built from 2eab64a999adfd3231de40cc1a96a6a723981c1d. This build ([rpminspect-1.11-0.1.202301311319git2eab64a](https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/build/5376033/)) also prints the section `per-inspection ignores` in the config dump:
```
per-inspection ignores:
    files:
        - /usr/lib/dracut
        - /usr/lib/udev
    debuginfo:
        - /lib/modules/*
        - /usr/lib/debug/.dwz/*
        - /usr/lib/grub/*
    shellsyntax:
        - /usr/lib*/pcsd/vendor/bundle/gems/thin*/lib/thin/controllers/*.erb
```
As well as the full shellsyntax config section:
```
shellsyntax:
    shells:
        - sh
        - ksh
        - zsh
        - csh
        - tcsh
        - rc
        - bash
    ignore:
        - /usr/lib*/pcsd/vendor/bundle/gems/thin*/lib/thin/controllers/*.erb
```
And then we have the next version ([1.11-0.1.202302012116git14b2d0b](https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/build/5395738/)), built from 14b2d0b3bf00ce10b8fd50172ebcf43728d644f0. This version no longer prints the `per-inspection ignores` section at all. The `shellsyntax` section no longer contains the erb rule from `rpminspect.yaml`:
```
shellsyntax:
    shells:
        - sh
        - ksh
        - zsh
        - csh
        - tcsh
        - rc
        - bash
```
This means that a bogus BAD result is present:
```
shellsyntax:
------------
1)
/usr/lib64/pcsd/vendor/bundle/gems/thin-1.8.1/lib/thin/controllers/service.sh.erb
is not a valid sh script on x86_64 

Result: BAD
Waiver Authorization: Anyone

Details:
/usr/lib64/pcsd/vendor/bundle/gems/thin-1.8.1/lib/thin/controllers/service.sh.erb: line 16: syntax error near unexpected token `newline'
/usr/lib64/pcsd/vendor/bundle/gems/thin-1.8.1/lib/thin/controllers/service.sh.erb: line 16: `DAEMON=<%= Command.script %>'

Suggested Remedy: The referenced shell script is invalid. Consider debugging it
with the '-n' option on the shell to find and fix the problem.
```

Neither of these versions prints the `xml` configuration but that one only fails if I remove `rpminspect.yaml` entirely.
