### ISSUE TITLE
rpmdeps ignores does not seem to be recognized

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#1098]
**Describe the bug**
Given the local rpminspect.yaml file:

```
---
inspections:
  # none of our compiled code has an ABI
  abidiff: off
  # at present the wrong debuginfo files are being used to run this check
  annocheck: off
  # the project does not use .desktop files
  desktop: off
  # the project uses no Java
  javabytecode: off

rpmdeps:
  # ignore auto dependencies like: (crate(bindgen/default) >= 0.59.0 with crate(bindgen/default) < 0.60.0~)'
  ignore:
    requires: ^\(crate\(.*\)$

...
```

The output of ```rpminspect --dump-config``` looks like:

```
...
rpmdeps:
    Requires:
...
```

**To Reproduce**
```# rpminspect-fedora --dump-config -v -a aarch64,src stratisd-3.4.4-2.fc38 stratisd-3.5.1-1.fc38```

**Expected behavior**
Would have liked to see the ```Requires:``` entry followed by some indication indicating that the specified ignores had been picked up.

**Environment:**
new copr build of rpminspect as of the morning of February 17.

**Additional notes: **
```# rpminspect-fedora -v -a aarch64,src stratisd-3.4.4-2.fc38 stratisd-3.5.1-1.fc38``` yielded a very long report from rpmdeps check of about 51 auto-generated requires, most looking like this:

```
2) Retained 'Requires: (crate(async-trait/default) >= 0.1.51 with
crate(async-trait/default) < 0.2.0~)' in source package stratisd; this is
expected

Result: INFO
Waiver Authorization: Not Waivable
```

Our intention is to ignore those entirely, rather than report them at info level, since they are all auto-generated from Cargo.toml.
