### ISSUE TITLE
locks up with incorrect profile yaml

### ISSUE THREAD

**Issue by bcl** [rpminspect/rpminspect#503]
If I create a profile that starts with `--` instead of `---` rpminspect will lock up and consume 100% CPU

eg.

`/usr/share/rpminspect/profiles/redhat/weldr-client.yaml`

```yaml
--
annocheck:
  - rhel-policy: --ignore-unknown --verbose --skip-cf-protection
```
