### ISSUE TITLE
rpminspect does not stop when profile name is invalid

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#590]
The current behavior where the profile is ignored when the profile name is not found could be misleading.

Could it be possible to make rpminspect stops and returns a proper error code ?

```
[fedora@ip-172-31-32-177 python3.9]$ rpminspect-centos -Dv -k -t VERIFY --profile=centos-stream-9-devel.yaml -w /data/rpminspect -a x86_64,noarch,src -o /home/fedora/zuul-output/logs/result.json -F json /data/rpminspect/python-setuptools_scm-5.0.1-4.el9 /data/rpminspect/python-setuptools_scm-6.0.1-1.el9 | head
rpminspect: *** unable to read profile 'centos-stream-9-devel.yaml' from (null)
: No such file or directory
rpminspect: *** unable to read profile 'centos-stream-9-devel.yaml' from (null)
: No such file or directory
# rpminspect configuration

---
common:
    workdir: /data/rpminspect
    profiledir: /usr/share/rpminspect/profiles/centos
koji:
    hub: http://kojihub.stream.centos.org/kojihub
    download_ursine: http://kojihub.stream.centos.org/kojifiles
    download_mbs: http://kojihub.stream.centos.org/kojifiles
[fedora@ip-172-31-32-177 python3.9]$ rpminspect-centos -Dv -k -t VERIFY --profile=centos-stream-9-devel -w /data/rpminspect -a x86_64,noarch,src -o /home/fedora/zuul-output/logs/result.json -F json /data/rpminspect/python-setuptools_scm-5.0.1-4.el9 /data/rpminspect/python-setuptools_scm-6.0.1-1.el9 | head
# rpminspect configuration

---
common:
    workdir: /data/rpminspect
    profiledir: /usr/share/rpminspect/profiles/centos
koji:
    hub: http://kojihub.stream.centos.org/kojihub
    download_ursine: http://kojihub.stream.centos.org/kojifiles
    download_mbs: http://kojihub.stream.centos.org/kojifiles

```
