### ISSUE TITLE
patches: ignore_list doesn't do anything

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#683]
From [generic.yaml](https://github.com/rpminspect/rpminspect/blob/master/data/generic.yaml#L677-L682):

```yaml
patches:
    # List of patch files to ignore in the 'patches' inspection.
    # These should match the name as specified on a PatchN: line in
    # the spec file.
    #ignore_list:
    #    - example.patch
```

However, rpminspect ignores the following local configuration:

```yaml
---
patches:
    ignore_list:
        - linux-kernel-test.patch
        - patch-5.14.0-redhat.patch
```

If I change the `ignore_list` to `ignore`, then rpminspect picks up the configuration:
```yaml
# rpminspect -D
# rpminspect configuration

---
common:
    workdir: /var/tmp/rpminspect
commands:
    diffstat: diffstat
    msgunfmt: msgunfmt
    desktop-file-validate: desktop-file-validate
    annocheck: annocheck
    abidiff: abidiff
    kmidiff: kmidiff
vendor:
    vendor_data_dir: /usr/share/rpminspect
    favor_release: newest
inspections:
    license: on
    emptyrpm: on
    lostpayload: on
    metadata: on
    manpage: on
    xml: on
    elf: on
    desktop: on
    disttag: on
    specname: on
    modularity: on
    javabytecode: on
    changedfiles: on
    movedfiles: on
    removedfiles: on
    addedfiles: on
    upstream: on
    ownership: on
    shellsyntax: on
    annocheck: on
    dsodeps: on
    filesize: on
    permissions: on
    capabilities: on
    kmod: on
    arch: on
    subpackages: on
    changelog: on
    pathmigration: on
    lto: on
    symlinks: on
    files: on
    types: on
    abidiff: on
    kmidiff: on
    config: on
    doc: on
    patches: on
    virus: on
    politics: on
    badfuncs: on
    runpath: on
    unicode: on
    rpmdeps: on
ignore:
    - linux-kernel-test.patch
    - patch-5.14.0-redhat.patch
desktop:
    desktop_entry_files_dir: /usr/share/applications
ownership:
    bin_paths:
        - /bin
        - /sbin
        - /usr/bin
        - /usr/sbin
    bin_owner: root
    bin_group: root
shellsyntax:
    shells:
        - sh
        - ksh
        - zsh
        - csh
        - tcsh
        - rc
        - bash
specname:
    match: full
    primary: name
abidiff:
    suppression_file: .abignore
    debuginfo_path: /usr/lib/debug/
    include_path: /usr/include/
    security_level_threshold: 2
kmidiff:
    suppression_file: .abignore
    debuginfo_path: /usr/lib/debug/
    kernel_filenames:
        - vmlinux
        - vmlinuz
patches:
    file_count_threshold: 20
    line_count_threshold: 5000
global ignores:
    - linux-kernel-test.patch
    - patch-5.14.0-redhat.patch

```

However, the ignored patches are listed in both `global ignores` and `ignore` sections. And not in `patches` section. Is that expected?

```shell
$ rpm -q rpminspect 
rpminspect-1.9-0.1.202203012203git.el9.x86_64
```
